"""Added is_active field to user table

Revision ID: 2409b97bd3bf
Revises: 32bc51953311
Create Date: 2022-11-28 21:04:10.525422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2409b97bd3bf'
down_revision = '32bc51953311'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
